package pl.ething.model;
// default package
// Generated 2016-09-18 18:30:32 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", catalog = "orm")
public class Contact implements java.io.Serializable {

	private Long id;
	private long userOwner;
	private long userProperty;
	private String status;

	public Contact() {
	}

	public Contact(long userOwner, long userProperty, String status) {
		this.userOwner = userOwner;
		this.userProperty = userProperty;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "USER_OWNER", nullable = false)
	public long getUserOwner() {
		return this.userOwner;
	}

	public void setUserOwner(long userOwner) {
		this.userOwner = userOwner;
	}

	@Column(name = "USER_PROPERTY", nullable = false)
	public long getUserProperty() {
		return this.userProperty;
	}

	public void setUserProperty(long userProperty) {
		this.userProperty = userProperty;
	}

	@Column(name = "STATUS", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
