package pl.ething.model;
// default package
// Generated 2016-09-18 18:30:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name = "message", catalog = "orm")
public class Message implements java.io.Serializable {

	private Long id;
	private long userOwner;
	private long userProperty;
	private Date dataTime;
	private String text;
	private byte[] image;
	private String type;

	public Message() {
	}

	public Message(long userOwner, long userProperty, Date dataTime, String text, String type) {
		this.userOwner = userOwner;
		this.userProperty = userProperty;
		this.dataTime = dataTime;
		this.text = text;
		this.type = type;
	}

	public Message(long userOwner, long userProperty, Date dataTime, String text, byte[] image, String type) {
		this.userOwner = userOwner;
		this.userProperty = userProperty;
		this.dataTime = dataTime;
		this.text = text;
		this.image = image;
		this.type = type;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "USER_OWNER", nullable = false)
	public long getUserOwner() {
		return this.userOwner;
	}

	public void setUserOwner(long userOwner) {
		this.userOwner = userOwner;
	}

	@Column(name = "USER_PROPERTY", nullable = false)
	public long getUserProperty() {
		return this.userProperty;
	}

	public void setUserProperty(long userProperty) {
		this.userProperty = userProperty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATA_TIME", nullable = false, length = 19)
	public Date getDataTime() {
		return this.dataTime;
	}

	public void setDataTime(Date dataTime) {
		this.dataTime = dataTime;
	}

	@Column(name = "TEXT", nullable = false, length = 512)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "IMAGE")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@Column(name = "TYPE", nullable = false, length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
