package pl.ething.model;
// default package
// Generated 2016-09-18 18:30:32 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "status", catalog = "orm", uniqueConstraints = @UniqueConstraint(columnNames = "USER"))
public class Status implements java.io.Serializable {

	private Long id;
	private long user;
	private String type;
	private String text;
	private Date lastActivity;

	public Status() {
	}

	public Status(long user, Date lastActivity) {
		this.user = user;
		this.lastActivity = lastActivity;
	}

	public Status(long user, String type, String text, Date lastActivity) {
		this.user = user;
		this.type = type;
		this.text = text;
		this.lastActivity = lastActivity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "USER", unique = true, nullable = false)
	public long getUser() {
		return this.user;
	}

	public void setUser(long user) {
		this.user = user;
	}

	@Column(name = "TYPE", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "TEXT")
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LAST_ACTIVITY", nullable = false, length = 19)
	public Date getLastActivity() {
		return this.lastActivity;
	}

	public void setLastActivity(Date lastActivity) {
		this.lastActivity = lastActivity;
	}

}
